!rop
meta: !meta
  opType: raytk.operators.combine.composeSdf
  opVersion: '2'
  opStatus: beta
opDef: !def
  enable: true
  typeSpec: !ropTypes
    coordType: !coordT
      Allcoordtype: true
    contextType: !contextT
      Allcontexttype: true
    returnType: !returnT
      Returntypesdf: true
  function: function
  paramGroupTable: params
  libraryNames: raytkCombine
  generatedMacroTables: multiInputHandler_macros
multiInput: !multiInput
  Minimuminputs: 1
  Coordtypereductionmode: common
  Coordtypereductionscope: '*'
  Contexttypereductionmode: common
  Contexttypereductionscope: '*'
  Returntypereductionmode: none
  inputs:
  - !input
    coordType: !coordT
      Allcoordtype: true
    contextType: !contextT
      Allcontexttype: true
    returnType: !returnT
      Returntypesdf: true
  - !input
    coordType: !coordT
      Allcoordtype: true
    contextType: !contextT
      Allcontexttype: true
    returnType: !returnT
      Returntypesdf: true
  - !input
    coordType: !coordT
      Allcoordtype: true
    contextType: !contextT
      Allcontexttype: true
    returnType: !returnT
      Returntypesdf: true
  - !input
    coordType: !coordT
      Allcoordtype: true
    contextType: !contextT
      Allcontexttype: true
    returnType: !returnT
      Returntypesdf: true
  - !input
    coordType: !coordT
      Allcoordtype: true
    contextType: !contextT
      Allcontexttype: true
    returnType: !returnT
      Returntypesdf: true
  - !input
    coordType: !coordT
      Allcoordtype: true
    contextType: !contextT
      Allcontexttype: true
    returnType: !returnT
      Returntypesdf: true
  - !input
    coordType: !coordT
      Allcoordtype: true
    contextType: !contextT
      Allcontexttype: true
    returnType: !returnT
      Returntypesdf: true
  - !input
    coordType: !coordT
      Allcoordtype: true
    contextType: !contextT
      Allcontexttype: true
    returnType: !returnT
      Returntypesdf: true
elements:
- !opElement
  name: combiner
  elementType: combiner
  params:
    Includenone: false
    Modeparam: ''
    Swapinputsparam: ''
    Radiusparam: ''
    Numberparam: ''
    Offsetparam: ''
    Radiusfield: ''
    Offsetfield: ''
    Numberfield: ''
    Manageparamstates: false
    Alwaysincludeallparams: true
    Switchmode: switch
    Indexexpr: mode
    Prepcodeplaceholder: MERGE_PREP();
    Bodycodeplaceholder: MERGE_BODY();
    Defaultinitcodeplaceholder: MERGE_DEFAULT_INIT();
- !opElement
  name: aggregateCodeGenerator
  elementType: aggregateCodeGenerator
  params:
    Startindex: 0
    Exprindexoffset: 0
    Reverseorder: false
    Initmode: separate
    Numberingmode: available
    Startstmt: ''
    Defaultstmt: ''
    Firststepstmt: ''
    Stepstmt: !expr
      expr: op('stepTemplate').text
    Bodycodeplaceholder: AGGREGATE_BODY();
